### ISSUE TITLE
Terraform Plan -target Option

### ISSUE THREAD

**Issue by Vadiraj-Puranik** [cloudnloud/weekly-cloud-engineer-interview-program#16]
I have 2 Files in the same directory as below 
ec2.tf
vpc.tf 
I want to specifically run terraform plan to only vpc.tf, I see we can destroy resources with -target option . 
So is there any terraform plan -target vpc.tf option or how can this be achieved?

**Comment by yeofrancis** [comment]
why did you want to tf plan only vpc.tf? is there a resource in vpc.tf that you want to include without destroying the whole infra.?

**Comment by Vadiraj-Puranik** [comment]
@yeofrancis basically I want to run only one file among 2 files in the same folder .
Is there any way we get this done without moving vpc.tf to another folder?

**Comment by yeofrancis** [comment]
You can, by using module

 

Thank you.

 

 

Best Regards,

Francis Yeo

Contact : +65 90543645

**Comment by Vadiraj-Puranik** [comment]
@yeofrancis This helps got an overview of modules 
Thank you very much
